### ISSUE TITLE
Deployment fails with a media service error in northcentralus

### ISSUE THREAD

**Issue by sdsd-dsd** [microsoft/PubSec-Info-Assistant#331] opened 2023-11-08 18:55 UTC
FYI - when I tried to deploy to LOCATION="northcentralus" I got the following error for the media service:

```
{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Creation of new Media Service accounts are not allowed as the resource has been deprecated.",
        "details": [
            {
                "code": "MediaServiceAccountCreationDisabled",
                "message": "Creation of new Media Service accounts are not allowed as the resource has been deprecated."
            }
        ]
    }
}
```

Changing to LOCATION="eastus" deployed without errors.

**Comment by dayland** [comment] 2024-02-19 20:35
Duplicate of #501

**Comment by lelong-adm4soa** [comment] 2024-02-21 22:55
Hello, I have run into this issue with new deployments. It appears the block went into place the end of Jan 2024 for New media Services, noted in the guide posted. Any news on the fix?

**Comment by georearl** [comment] 2024-02-21 23:04
This has been addressed with a PR in main - you should not be seeing issues now if you pull latest

**Closed** 2024-02-21 23:07 UTC
Labels: enhancement
