### ISSUE TITLE
Upload of Json file hanging

### ISSUE THREAD

**Issue by rashodqaim** [microsoft/PubSec-Info-Assistant#580] opened 2024-03-20 14:48 UTC
Upload a Json file on Friday March 15th and file is still not loaded. Status of file says Queued. Here is the log file from Cosmo DB 

{
    "id": "dXBsb2FkL0NsaW5pY2FsX3RyYWlscy9jbGluaWNhbF90cmFpbHMuanNvbg==",
    "file_path": "upload/Clinical_trails/clinical_trails.json",
    "file_name": "clinical_trails.json",
    "state": "Queued",
    "start_timestamp": "2024-03-15 18:55:59",
    "state_description": "",
    "state_timestamp": "2024-03-15 19:26:35",
    "status_updates": [
        {
            "status": "File uploaded from browser to Azure Blob Storage",
            "status_timestamp": "2024-03-15 18:55:59",
            "status_classification": "Info"
        },
        {
            "status": "Pipeline triggered by Blob Upload",
            "status_timestamp": "2024-03-15 18:56:09",
            "status_classification": "Info"
        },
        {
            "status": "FileUploadedFunc - FileUploadedFunc function started",
            "status_timestamp": "2024-03-15 18:56:09",
            "status_classification": "Debug"
        },
        {
            "status": "FileUploadedFunc - json file sent to submit queue. Visible in 249 seconds",
            "status_timestamp": "2024-03-15 18:56:09",
            "status_classification": "Debug"
        },
        {
            "status": "FileLayoutParsingOther - Starting to parse the non-PDF file",
            "status_timestamp": "2024-03-15 19:00:43",
            "status_classification": "Info"
        },
        {
            "status": "FileLayoutParsingOther - Message received from non-pdf submit queue",
            "status_timestamp": "2024-03-15 19:00:43",
            "status_classification": "Debug"
        },
        {
            "status": "FileLayoutParsingOther - SAS token generated to access the file",
            "status_timestamp": "2024-03-15 19:00:43",
            "status_classification": "Debug"
        },
        {
            "status": "FileLayoutParsingOther - partitioning complete",
            "status_timestamp": "2024-03-15 19:03:49",
            "status_classification": "Debug"
        },
        {
            "status": "FileLayoutParsingOther - chunking complete. 19021 chunks created",
            "status_timestamp": "2024-03-15 19:03:52",
            "status_classification": "Debug"
        },
        {
            "status": "FileLayoutParsingOther - chunking stored.",
            "status_timestamp": "2024-03-15 19:26:35",
            "status_classification": "Debug"
        },
        {
            "status": "FileLayoutParsingOther - message sent to enrichment queue",
            "status_timestamp": "2024-03-15 19:26:35",
            "status_classification": "Debug"
        }
    ],
    "_rid": "5hNMAOg52NbbAAAAAAAAAA==",
    "_self": "dbs/5hNMAA==/colls/5hNMAOg52NY=/docs/5hNMAOg52NbbAAAAAAAAAA==/",
    "_etag": "\"13006aeb-0000-0100-0000-65f4a0eb0000\"",
    "_attachments": "attachments/",
    "_ts": 1710530795
}
![error1](https://github.com/microsoft/PubSec-Info-Assistant/assets/12738486/1d17ccff-77b3-4721-94f7-a6aab8e83bee)
![error2](https://github.com/microsoft/PubSec-Info-Assistant/assets/12738486/767ef9a4-185a-42dd-8a15-a31ac2de5fa4)

**Comment by rashodqaim** [comment] 2024-03-28 15:40
I have sent over the email, with the files that are not uploading. Please let me know if there is anything else that you need from me.

**Comment by georearl** [comment] 2024-04-08 17:31
Closing this as it seems the issue is related to large csv processing which was fixed in a recent push to main. If you encounter this do a pull from main, rebuild the functions app and resubmit the files.

**Closed by georearl** 2024-04-08 17:31 UTC
Labels: bug
